services:
  db:
    container_name: rag-postgres
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./fixtures:/app/fixtures
    environment:
      DB_HOST: db
      DB_PORT: 5432
      OPENAI_API_KEY: ${OPENAI_API_KEY}


volumes:
  pgdata:
